version: '3.0'

services:
  api:
    image: node:alpine
    container_name: mongo-node-api
    command: sh -c "npm install && npm run watch"
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8080:3000"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: tdmongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
    - ./data:/data
